### ISSUE TITLE
Unable to open visdial_data.h5

### ISSUE THREAD

**Issue by YuCosine** [idansc/mrr-ndcg#3]
Hi,

Thanks for the great work on Visual Dialog.

I download the data from your link and try running the notebook. However, the line 
```
h5 = h5py.File("data/visdial_data.h5", 'r')
```
raises an error
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/h5py/_hl/files.py", line 408, in __init__
    swmr=swmr)
  File "/usr/local/lib/python3.7/site-packages/h5py/_hl/files.py", line 173, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 88, in h5py.h5f.open
OSError: Unable to open file (truncated file: eof = 500662272, sblock->base_addr = 0, stored_eof = 819600624)
```

I google this error and find it likely that the file `visdial_data.h5` is corrupted.
Could you please upload the file again?

Thank you.

**Comment by idansc** [comment]
Thanks for reporting. 
Can you check if it works now?

Additionally, you can download the file here:
https://filebox.ece.vt.edu/~jiasenlu/codeRelease/visDial.pytorch/data/

**Comment by YuCosine** [comment]
> Thanks for reporting.
> Can you check if it works now?
> 
> Additionally, you can download the file here:
> https://filebox.ece.vt.edu/~jiasenlu/codeRelease/visDial.pytorch/data/

The link in README works now.
Thanks a lot!
